// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAV2fjW5ARr_tL1HiXNmCOV9iCs8XWiuw',
    appId: '1:250122353409:web:09f1a30dd0e40c3cbf3900',
    messagingSenderId: '250122353409',
    projectId: 'captus-2c79a',
    authDomain: 'captus-2c79a.firebaseapp.com',
    storageBucket: 'captus-2c79a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQh855-ypTW0o37Nqi_pl-2dRgVRR2ACA',
    appId: '1:250122353409:android:25f48df6905e8211bf3900',
    messagingSenderId: '250122353409',
    projectId: 'captus-2c79a',
    storageBucket: 'captus-2c79a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBclK0gyHyihtYq0R3NsMhpIp-lr5ydJLM',
    appId: '1:250122353409:ios:c155d8e15f3a6c90bf3900',
    messagingSenderId: '250122353409',
    projectId: 'captus-2c79a',
    storageBucket: 'captus-2c79a.firebasestorage.app',
    iosBundleId: 'com.example.captusMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBclK0gyHyihtYq0R3NsMhpIp-lr5ydJLM',
    appId: '1:250122353409:ios:c155d8e15f3a6c90bf3900',
    messagingSenderId: '250122353409',
    projectId: 'captus-2c79a',
    storageBucket: 'captus-2c79a.firebasestorage.app',
    iosBundleId: 'com.example.captusMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAV2fjW5ARr_tL1HiXNmCOV9iCs8XWiuw',
    appId: '1:250122353409:web:76c78dd189a894c3bf3900',
    messagingSenderId: '250122353409',
    projectId: 'captus-2c79a',
    authDomain: 'captus-2c79a.firebaseapp.com',
    storageBucket: 'captus-2c79a.firebasestorage.app',
  );
}
